In [1]:
import numpy as np

In [8]:
def svd_update(U, S, V, X, c = None, update = False, downdate = False):
    V = np.vstack([V, np.zeros(V.shape[1])])
    if downdate or type(c) == type(np.array([])):
        b = np.zeros(V.shape[0])
        b[-1] = 1
        b = np.reshape(b, (b.shape[0], 1))
        if downdate:
            a = np.reshape(np.multiply(X[:,-1], -1), (-1, 1))
        elif update:
            a = np.reshape(c, (-1, 1))
        else:
            a = np.reshape(X[:,-1] - c, (-1, 1))
    else:
        ones = np.zeros(V.shape[0])
        ones = np.add(b, 1)
        b = np.reshape(ones, (-1, 1))
        a = np.reshape(np.multiply((-1/X.shape[1]), np.dot(X, b)), (-1, 1))
    m = np.reshape(np.dot(np.transpose(U), a), (-1, 1))
    p = np.reshape(a - np.dot(U, m), (-1, 1))
    Ra = np.linalg.norm(p)
    P = np.reshape(np.multiply((1 / Ra), p), (-1, 1))
    n = np.reshape(np.dot(np.transpose(V), b), (-1, 1))
    q = b - np.dot(V, n)
    Rb = np.linalg.norm(q)
    Q = np.reshape(np.multiply((1 / Rb), q), (-1, 1))
    k = S
    K = np.zeros((k.shape[0] + 1, k.shape[0] + 1))
    K[:-1,:-1] = k
    stack = np.vstack(np.append(m, Ra))
    t = np.reshape(np.append(n, Rb), (1, -1))
    dot = np.dot(stack, t)
    K = np.add(K, dot)
    D, P = np.linalg.eig(K)
    return (np.transpose(np.linalg.inv(P)), np.diag(D), P)

In [9]:
X = np.array([[1.0,2.0,3.0,4.0],[3.0,2.0,5.0,5.0],[5.0,3.0,1.0,1.0],[7.0,7.0,7.0,7.0]])
U, s, V = np.linalg.svd(X, full_matrices = False)
print(U, s, V)
a = np.reshape(np.array([4.0,5.0,1.0,7.0]), (-1, 1))
U, S, V = svd_update(U, np.diag(s), V, X, a, update = True)
print(U, S, V)

[[-0.29150126 -0.43954828  0.37169658 -0.76398036]
 [-0.43807129 -0.43585658 -0.78539221  0.03580033]
 [-0.28073796  0.77514628 -0.29558342 -0.48266436]
 [-0.80268721  0.12639064  0.39702793  0.42671708]] [17.41285951  4.44700622  1.30795466  0.5529139 ] [[-0.49550824 -0.454846   -0.51481542 -0.531556  ]
 [ 0.67761269  0.32816765 -0.41332234 -0.51216373]
 [-0.52234351  0.81428969 -0.2509714   0.03321015]
 [-0.14989959  0.14951056  0.7079146  -0.67382017]]
[[ 1.          0.          0.          0.          0.        ]
 [ 0.          1.          0.          0.          0.        ]
 [ 0.          0.          1.          0.          0.        ]
 [ 0.          0.          0.          1.          0.        ]
 [-0.531556   -0.51216373  0.03321015 -0.67382017  1.41421356]] [[1.74128595e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 4.44700622e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.30795466e+00 0.00000000e+00
  

In [17]:
Z=np.reshape(X,(X.shape[0],1))
Z

ValueError: cannot reshape array of size 20 into shape (5,1)

In [18]:
C=X.T
C

array([[ 1.,  3.,  5.,  7.,  1.],
       [ 2.,  2.,  3.,  7.,  2.],
       [ 3.,  5.,  1.,  7.,  3.],
       [ 4.,  5.,  1.,  7.,  4.]])

In [25]:
b = np.zeros(10)
b[-1] = 1
b = np.reshape(b, (b.shape[0], 1))
b

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.]])

In [34]:
ones = np.ones(10)
b = np.reshape(ones, (-1, 1))
b

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [45]:
A = np.array([[1.0,2.0,3.0,4.0],[3.0,2.0,5.0,5.0],[5.0,3.0,1.0,1.0],[7.0,7.0,7.0,7.0]])
c = np.eye(np.shape(A)[1])
c

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [53]:
import numpy as np

def svd_update(U, S, V, X, c = None, update = False, downdate = False):


    V = np.vstack([V, np.zeros(V.shape[1])])
    if downdate or type(c) == type(np.array([])):
        b = np.zeros(V.shape[0])
        b[-1] = 1
        b = np.reshape(b, (b.shape[0], 1))
        if downdate:
            a = np.reshape(np.multiply(X[:,-1], -1), (-1, 1))
        elif update:
            a = np.reshape(c, (-1, 1))
        else:
            a = np.reshape(X[:,-1] - c, (-1, 1))
    else:
        ones = np.ones(V.shape[0])
        b = np.reshape(ones, (-1, 1))
        a = np.reshape(np.multiply((-1/X.shape[1]), np.dot(X, b)), (-1, 1))

    m = np.reshape(np.dot(np.transpose(U), a), (-1, 1))
    p = np.reshape(a - np.dot(U, m), (-1, 1))
    Ra = np.linalg.norm(p)
    P = np.reshape(np.multiply((1 / Ra), p), (-1, 1))
    n = np.reshape(np.dot(np.transpose(V), b), (-1, 1))
    q = b - np.dot(V, n)
    Rb = np.linalg.norm(q)
    Q = np.reshape(np.multiply((1 / Rb), q), (-1, 1))

    k = S
    K = np.zeros((k.shape[0] + 1, k.shape[0] + 1))
    K[:-1,:-1] = k
    stack = np.vstack(np.append(m, Ra))
    t = np.reshape(np.append(n, Rb), (1, -1))
    dot = np.dot(stack, t)
    K = np.add(K, dot)

    D, P = np.linalg.eig(K)

    return (np.transpose(np.linalg.inv(P)), np.diag(D), P)

In [49]:
X = np.array([[1.0,2.0,3.0,4.0],[3.0,2.0,5.0,5.0],[5.0,3.0,1.0,1.0],[7.0,7.0,7.0,7.0]])
U, s, V = np.linalg.svd(X, full_matrices = False)
a = np.reshape(np.array([4.0,5.0,1.0,7.0]), (-1, 1))
U, S, V = svd_update(U, np.diag(s), V, X, a, update = True)

In [50]:
X = np.array([[1.0,2.0,3.0,4.0],[3.0,2.0,5.0,5.0],[5.0,3.0,1.0,1.0],[7.0,7.0,7.0,7.0]])
U, s, V = np.linalg.svd(X, full_matrices = False)
U, S, V = svd_update(U, np.diag(s), V, X, downdate = True)

In [51]:
X = np.array([[1.0,2.0,3.0,4.0],[3.0,2.0,5.0,5.0],[5.0,3.0,1.0,1.0],[7.0,7.0,7.0,7.0]])
U, s, V = np.linalg.svd(X, full_matrices = False)
a = np.reshape(np.array([4.0,5.0,1.0,7.0]), (-1, 1))
U, S, V = svd_update(U, np.diag(s), V, X, a)

ValueError: shapes (4,4) and (16,1) not aligned: 4 (dim 1) != 16 (dim 0)

In [54]:
X = np.array([[1.0,2.0,3.0,4.0],[3.0,2.0,5.0,5.0],[5.0,3.0,1.0,1.0],[7.0,7.0,7.0,7.0]])
U, s, V = np.linalg.svd(X, full_matrices = False)
U, S, V = svd_update(U, np.diag(s), V, X)

ValueError: shapes (4,4) and (5,1) not aligned: 4 (dim 1) != 5 (dim 0)

In [ ]:
import time
import pandas as pd

RANK = 1
N_COLS = 10

def evaluate_svd(svd_fn, reconstruct_fn, min_rows=10, max_rows=50, n_samples=10, n_cols=N_COLS, rank=RANK, random_seed=0):
    np.random.seed(random_seed)
    elapsed_times = []
    errors = []
    n_rows_array = np.random.randint(low=min_rows, high=max_rows + 1, size=n_samples)
    n_rows_array.sort()
    
    for n_rows in n_rows_array:
        # construct a low-rank matrix
        left = np.random.randn(n_rows, rank)
        right = np.random.randn(rank, n_cols)
        full = np.dot(left, right)

        # how long does it take to perform the SVD?
        start_t = time.time()
        svd_outputs = svd_fn(full)
        end_t = time.time()
        elapsed_t = end_t - start_t
        elapsed_times.append(elapsed_t)

        # compute mean absolte error of reconstruction 
        reconstructed = reconstruct_fn(svd_outputs)
        diff = full - reconstructed
        mae = np.mean(np.abs(diff))
        errors.append(mae)
        print("n_rows=%d ==> time = %0.4f, MAE = %0.8f" % (n_rows, elapsed_t, mae))
    max_error = np.max(errors)
    print("Max Error=%f" % max_error)
    assert max_error < 0.0000001
    return n_rows_array, elapsed_times, errors 

def np_svd(X):
    return np.linalg.svd(X, full_matrices=False, compute_uv=True)

def np_inv_svd(svd_outputs):
    U, s, V = svd_outputs
    return np.dot(U, np.dot(np.diag(s), V))

In [ ]:
n_rows, np_times, np_errors = evaluate_svd(np_svd, np_inv_svd)